#!/usr/bin/python
import os
import argparse
from devlogger import devlog
from tasks import TaskManager

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument("-lt", "--longterm", help="Modify long-term tasks", dest='lt', action="store_true")
    parser.add_argument("-w", "--wait", help="Modify Wait/Watcher tasks list", dest='w', action='store_true')
    parser.add_argument('-bl', '--backlog', help="Modify Backlog tasks list", dest='bl', action='store_true')
    parser.add_argument("-a", "--append", help="add a task to the end of the list", dest='a', action='store_true')
    parser.add_argument("-p", "--prepend", help="add a task to the beginning of the list", dest='p', action='store_true')
    parser.add_argument("-d", "--delete", help="delete the task at the given index", dest='d', type=int)
    parser.add_argument("-ct", "--changetype", help="change task at given index to new task type", dest='ct', type=int)
    parser.add_argument("-mu", "--moveup", help="move the selected task up in priority", dest='mu', type=int)
    parser.add_argument("-md", "--movedown", help="move the selected task down in priority", dest='md', type=int)
    parser.add_argument("-m1", "--promote", help="promote the selected task to top priority", dest='m1', type=int)
    parser.add_argument("-ml", "--demote", help="demote the selected task to bottom priority", dest='ml', type=int)
    parser.add_argument("-cd", "--change-list", help="Change lists", dest = 'cd')
    parser.add_argument("-rm", "--delete-list", help="Delete a list", dest = 'rm')
    parser.add_argument("-ls", "--list-lists", help="lists the ... lists", dest = 'ls', action="store_true")
    parser.add_argument("-mv", "--rename-list", help="rename the list", dest = 'mv')
    parser.add_argument("-f", "--finish", help="finish/log the task", dest='f', type=int)
    args = parser.parse_args()

    tsk_mgr = TaskManager()


    if args.lt:
        tsk_mgr.set_mode(LONGTERM)
    elif args.w:
        tsk_mgr.set_mode(WAIT)
    elif args.bl:
        tsk_mgr.set_mode(BACKLOG)

    if args.ls:
        tsk_mgr.show_lists()
    elif args.rm != None:
        tsk_mgr.remove_list(args.m)
    elif args.cd != None:
        tsk_mgr.change_default(args.cd)
        tsk_mgr.display()
    elif args.d != None:
        tsk_mgr.delete_task(args.d)
        tsk_mgr.display()
    elif args.f != None:
        tsk_mgr.finish_task(args.f)
        tsk_mgr.display()
    elif args.ct != None:
        tsk_mgr.change_type(args.ct)
        tsk_mgr.display()
    elif args.mu != None:
        tsk_mgr.move_task(args.mu, direction=UP)
        tsk_mgr.display()
    elif args.md != None:
        tsk_mgr.move_task(args.md, direction=DOWN)
        tsk_mgr.display()
    elif args.m1 != None:
        tsk_mgr.move_task(args.m1, new_slot=FIRST)
        tsk_mgr.display()
    elif args.ml != None:
        tsk_mgr.move_task(args.ml, new_slot=LAST)
        tsk_mgr.display()
    elif args.a:
        tsk_mgr.append_task()
        tsk_mgr.display()
    elif args.p:
        tsk_mgr.prepend_task()
        tsk_mgr.display()
    elif args.mv != None:
        tsk_mgr.move_list(args.mv)
        tsk_mgr.display()
    else:
        tsk_mgr.display()

